const jobsData = [
    {
        id: "job-1",
        title: "SDE Intern",
        company: "Amazon",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "DSA", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k/month Internship",
        applyUrl: "#",
        description: "Join Amazon's core e-commerce team as an SDE intern. You will work on robust backend systems handling millions of daily transactions. Strong grasp of Data Structures and Algorithms is required."
    },
    {
        id: "job-2",
        title: "Frontend Intern",
        company: "Flipkart",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "JavaScript", "HTML/CSS"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "₹30k/month Internship",
        applyUrl: "#",
        description: "Flipkart is looking for an enthusiastic Frontend Intern to build seamless, high-performance UI components for our mobile web interface. Excellent problem-solving skills and a passion for web performance."
    },
    {
        id: "job-3",
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C++", "Python", "SQL"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "TCS is hiring fresh engineering graduates. You will undergo extensive training followed by project deployment in enterprise solutions, banking, or healthcare domains."
    },
    {
        id: "job-4",
        title: "React Developer (1-3)",
        company: "Swiggy",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React.js", "Redux", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Swiggy's consumer web team is seeking a dedicated React developer. You'll build and maintain critical ordering flows, ensuring sub-second load times and a premium user experience."
    },
    {
        id: "job-5",
        title: "Junior Backend Developer",
        company: "Razorpay",
        location: "Bengaluru",
        mode: "Remote",
        experience: "0-1",
        skills: ["Node.js", "Express", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Work on Razorpay's high-scale payment API infrastructure. This role involves maintaining existing microservices, writing unit tests, and designing high-reliability endpoints."
    },
    {
        id: "job-6",
        title: "Java Developer",
        company: "Infosys",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "MySQL"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "Infosys is looking for junior Java developers for a fast-paced client project. You will implement REST APIs, integrate database operations, and ensure high code coverage."
    },
    {
        id: "job-7",
        title: "Python Developer",
        company: "Wipro",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Django", "REST APIs"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "Join Wipro's emerging tech division. The role involves developing scalable Python automation scripts and REST APIs. Good understanding of OOP principles is a must."
    },
    {
        id: "job-8",
        title: "Data Analyst Intern",
        company: "PhonePe",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["SQL", "Excel", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹25k–₹35k/month Internship",
        applyUrl: "#",
        description: "PhonePe's analytics team needs interns to run data models, create dashboards, and help drive business insights across millions of merchant transactions."
    },
    {
        id: "job-9",
        title: "QA Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Java"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "#",
        description: "Paytm is looking for sharp QA interns to ensure our app updates are bug-free. You will write test cases, automate regression tests, and collaborate directly with product managers."
    },
    {
        id: "job-10",
        title: "Fullstack Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "JavaScript", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Zoho is actively hiring fullstack engineers. Work on our core suite of enterprise products. We prefer candidates passionate about building software from scratch without heavy frameworks."
    },
    {
        id: "job-11",
        title: "DevOps Engineer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["AWS", "Kubernetes", "CI/CD"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Freshworks needs an energetic DevOps engineer to handle automated deployments and monitor cluster health. Experience with Docker and Terraform is highly preferred."
    },
    {
        id: "job-12",
        title: "Backend Developer",
        company: "CRED",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Golang", "Microservices", "Kafka"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "CRED is expanding its backend team to handle huge spikes in concurrent users. You will architect Golang microservices and manage real-time queues for seamless member reward experiences."
    },
    {
        id: "job-13",
        title: "Android Intern",
        company: "Juspay",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Kotlin", "Android Studio", "API Integration"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "₹30k/month Internship",
        applyUrl: "#",
        description: "Help build the next-generation payment SDK at Juspay. You'll be profiling Android app performance, fixing bugs, and integrating secure payment modules."
    },
    {
        id: "job-14",
        title: "System Administrator",
        company: "IBM",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Linux", "Networking", "Bash"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "IBM requires a system admin to manage our internal cloud infrastructure. RedHat certification is a plus. Strong troubleshooting and networking fundamentals are essential."
    },
    {
        id: "job-15",
        title: "Frontend Engineer",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "3-5",
        skills: ["React", "Redux", "WebPack"],
        source: "LinkedIn",
        postedDaysAgo: 8,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Oracle is modernizing its enterprise UI. We need an experienced Frontend Engineer capable of handling complex state management and building accessible web components."
    },
    {
        id: "job-16",
        title: "Integration Specialist",
        company: "SAP",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["ABAP", "Java", "SAP PI/PO"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Join SAP to help global clients integrate their systems with our cloud software. A keen eye for architecture and strong communication skills are required."
    },
    {
        id: "job-17",
        title: "React Developer",
        company: "Accenture",
        location: "Gurugram",
        mode: "Remote",
        experience: "0-1",
        skills: ["React", "CSS", "Hooks"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "Accenture is looking for junior React developers for an exciting new global client project. Must have strong understanding of React hooks and responsive CSS."
    },
    {
        id: "job-18",
        title: "Software Engineer",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["C#", ".NET", "SQL Server"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Capgemini is hiring .NET developers to maintain and upgrade legacy financial applications. Required experience in MVC, Web API, and SQL performance tuning."
    },
    {
        id: "job-19",
        title: "Machine Learning Intern",
        company: "Cognizant",
        location: "Chennai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "TensorFlow", "Pandas"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹20k/month Internship",
        applyUrl: "#",
        description: "Cognizant AI Labs is seeking interns to profile datasets, build baseline NLP models, and automate data cleaning pipelines for retail clients."
    },
    {
        id: "job-20",
        title: "Technical Support Engineer",
        company: "Dell",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Windows", "Hardware", "Troubleshooting"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "Provide enterprise-level technical support for Dell's corporate clients. Excellent communication skills and a deep understanding of hardware setups are necessary."
    },
    {
        id: "job-21",
        title: "Product Designer",
        company: "Zerodha",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Figma", "UI/UX", "Prototyping"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Zerodha wants a product designer to simplify trading interfaces. You will conduct user research, create wireframes, and design high-fidelity components used by millions."
    },
    {
        id: "job-22",
        title: "Backend Intern",
        company: "Postman",
        location: "Bengaluru",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Node.js", "APIs", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k/month Internship",
        applyUrl: "#",
        description: "Postman is hiring interns for our API client team. You will write internal tooling, optimize API response times, and ship code directly to production."
    },
    {
        id: "job-23",
        title: "SDE 1",
        company: "Groww",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Join Groww's investment team. You'll build reliable backend services that parse huge volumes of market data and handle mutual fund executions."
    },
    {
        id: "job-24",
        title: "iOS Developer",
        company: "Zepto",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Swift", "iOS", "CoreData"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Zepto is hiring iOS developers to optimize our 10-minute delivery app. We need engineers who care about smooth animations, battery efficiency, and robust offline caching."
    },
    {
        id: "job-25",
        title: "Data Engineer",
        company: "Dunzo",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Spark", "Python", "Airflow"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Dunzo needs a Data Engineer to build big-data pipelines for real-time order tracking and route optimization. Experience with distributed processing is mandatory."
    },
    {
        id: "job-26",
        title: "Junior Backend Developer",
        company: "TCS",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Hibernate", "Spring"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "TCS requires junior backend developers for a banking domain project. Strong understanding of core Java and SQL optimization is essential."
    },
    {
        id: "job-27",
        title: "Python Developer (Fresher)",
        company: "Infosys",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Flask", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "Infosys is running a Python excellence program. We are hiring freshers who have built strong personal projects in Flask or Django and have excellent problem-solving logic."
    },
    {
        id: "job-28",
        title: "Frontend Intern",
        company: "Razorpay",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "CSS", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹35k/month Internship",
        applyUrl: "#",
        description: "Razorpay design team is seeking interns to help build our internal UI component library. You will write rigorous tests and ensure cross-browser compatibility."
    },
    {
        id: "job-29",
        title: "React Developer (1-3)",
        company: "Wipro",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "JavaScript", "Redux"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Wipro seeks React developers for a large healthcare portal rewrite. Candidates must be comfortable with complex Redux stores and integration with legacy REST APIs."
    },
    {
        id: "job-30",
        title: "SDE Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Node.js", "MongoDB", "Data Structures"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹25k/month Internship",
        applyUrl: "#",
        description: "Paytm's wealth management wing is looking for passionate SDE interns. Expect to learn heavily about scaling NodeJS backends and securing sensitive financial data."
    },
    {
        id: "job-31",
        title: "Graduate Engineer Trainee",
        company: "Capgemini",
        location: "Pune",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "C++", "SQL"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "Capgemini is onboarding trainees for its cloud division. Comprehensive Bootcamp provided. A rigorous coding round is required for selection."
    },
    {
        id: "job-32",
        title: "Data Analyst Intern",
        company: "CRED",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["SQL", "Tableau", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k/month Internship",
        applyUrl: "#",
        description: "Join CRED's fast-paced analytics team. You will analyze drop-off rates, support growth experiments, and write complex SQL queries daily."
    },
    {
        id: "job-33",
        title: "UI/UX Designer",
        company: "Swiggy",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Figma", "Interaction Design", "Prototyping"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Swiggy is searching for an experienced UI/UX designer to revamp our delivery partner app. Empathy for the driver's environment and quick execution is key."
    },
    {
        id: "job-34",
        title: "QA Intern",
        company: "Flipkart",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Manual Testing", "Java", "Appium"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "₹30k/month Internship",
        applyUrl: "#",
        description: "Flipkart's mobile app testing team needs QA interns. You will run daily sanity checks, automate specific flows using Appium, and assist release managers."
    },
    {
        id: "job-35",
        title: "Security Engineer",
        company: "Amazon",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Cybersecurity", "Pen Testing", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Amazon Web Services requires a seasoned security engineer to perform threat modeling, infrastructure penetration testing, and code audits on early-stage services."
    },
    {
        id: "job-36",
        title: "DevOps Engineer",
        company: "Cognizant",
        location: "Mumbai",
        mode: "Remote",
        experience: "1-3",
        skills: ["Azure", "Jenkins", "Docker"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Cognizant is hiring Azure DevOps engineers to help transition enterprise clients to the cloud. You will set up CI/CD pipelines and infrastructure as code."
    },
    {
        id: "job-37",
        title: "Junior Backend Developer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Ruby on Rails", "MySQL", "Git"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Freshworks is expanding its core CRM backend team. We are looking for ruby enthusiasts who can write clean, test-driven backend logic and optimize database queries."
    },
    {
        id: "job-38",
        title: "React Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Ember.js", "React", "JavaScript"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Zoho needs frontend engineers capable of migrating legacy applications to modern React architectures while ensuring zero regression in user workflows."
    },
    {
        id: "job-39",
        title: "Python Developer",
        company: "Accenture",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "FastAPI", "Docker"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Accenture seeks Python developers experienced in FastAPI for building high-performance microservices. Experience with containerization is a huge plus."
    },
    {
        id: "job-40",
        title: "SDE Intern",
        company: "Juspay",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Haskell", "PureScript", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹40k/month Internship",
        applyUrl: "#",
        description: "Juspay is heavily invested in functional programming. We are looking for interns who are passionate about learning Haskell/PureScript and solving complex distributed systems problems."
    },
    {
        id: "job-41",
        title: "Java Developer (0-1)",
        company: "Oracle",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java 11", "Spring Boot", "REST"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Join Oracle's Cloud Infrastructure team as a Junior Java Developer. You'll contribute to high-availability control planes taking enterprise workloads."
    },
    {
        id: "job-42",
        title: "Graduate Engineer Trainee",
        company: "IBM",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "SQL", "Cloud Basics"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "IBM is looking for fresh talent for its Consulting wing. Training provided on AI and Cloud tools before deployment into challenging customer projects."
    },
    {
        id: "job-43",
        title: "React Developer (1-3)",
        company: "Flipkart",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React Native", "Redux", "JS"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Flipkart is scaling its React Native team for the mobile app checkout flow. We need developers who understand native bridges and render optimizations."
    },
    {
        id: "job-44",
        title: "Data Scientist",
        company: "Amazon",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Python", "Machine Learning", "AWS SageMaker"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Amazon's supply chain team needs a Data Scientist to build demand forecasting models. Experience deploying ML models to production is heavily preferred."
    },
    {
        id: "job-45",
        title: "Frontend Intern",
        company: "PhonePe",
        location: "Pune",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["React", "CSS", "Responsive Design"],
        source: "LinkedIn",
        postedDaysAgo: 9,
        salaryRange: "₹30k/month Internship",
        applyUrl: "#",
        description: "PhonePe is looking for a Frontend Intern to help develop partner portal dashboards. A good understanding of responsive design and CSS grids is expected."
    },
    {
        id: "job-46",
        title: "Game Developer",
        company: "Swiggy",
        location: "Bengaluru",
        mode: "Remote",
        experience: "1-3",
        skills: ["Phaser.js", "JavaScript", "HTML5"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Swiggy's engagement team wants a web game developer to build interactive minigames for consumers during IPL and festive seasons."
    },
    {
        id: "job-47",
        title: "Junior Backend Developer",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Microservices", "Redis"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Paytm's core payment gateway team expects you to handle highly concurrent requests on Java spring boot microservices. Focus will be on latency reduction."
    },
    {
        id: "job-48",
        title: "SAP Consultant",
        company: "SAP",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["SAP FICO", "ERP", "Consulting"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "SAP needs an experienced consultant capable of guiding Fortune 500 banks through major digital transformations utilizing SAP FICO."
    },
    {
        id: "job-49",
        title: "SDE Intern",
        company: "Zepto",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Django", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹35k/month Internship",
        applyUrl: "#",
        description: "Zepto's rapid delivery backend needs an intern to patch bugs, write monitoring scripts, and optimize Django ORM queries."
    },
    {
        id: "job-50",
        title: "Python Developer (Fresher)",
        company: "TCS",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Scripting", "Linux"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "TCS requires fresh python developers for testing and automation COE. You will build and maintain automation testing frameworks for major clients."
    },
    {
        id: "job-51",
        title: "QA Intern",
        company: "Razorpay",
        location: "Bengaluru",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Cypress", "JavaScript", "API Testing"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "₹20k/month Internship",
        applyUrl: "#",
        description: "Razorpay offers a QA internship focused entirely on automated UI testing using Cypress. You will be instrumental in preventing regressions before deployment."
    },
    {
        id: "job-52",
        title: "Graduate Engineer Trainee",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C", "C++", "Java"],
        source: "Naukri",
        postedDaysAgo: 10,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "Wipro's traditional campus hiring route. Looking for problem solvers willing to adapt to various legacy and modern technologies as per project needs."
    },
    {
        id: "job-53",
        title: "Cloud Support Engineer",
        company: "Amazon",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["AWS", "Networking", "Troubleshooting"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "AWS Premium Support is hiring engineers to interact with customers, reproduce issues, and collaborate with service teams to fix deep cloud infrastructure bugs."
    },
    {
        id: "job-54",
        title: "Data Analyst Intern",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Analytics", "SQL", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹25k/month Internship",
        applyUrl: "#",
        description: "Zoho's marketing group requires a data analyst intern to track campaign efficiency, conduct A/B test analysis, and create internal metric dashboards."
    },
    {
        id: "job-55",
        title: "React Developer (1-3)",
        company: "Infosys",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Material-UI", "REST API"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Infosys seeks React engineers for a tier-1 banking client. Strict adherence to security and WCAG accessibility standards is a major part of this role."
    },
    {
        id: "job-56",
        title: "Frontend Intern",
        company: "Groww",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["HTML", "CSS", "Javascript"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "₹30k/month Internship",
        applyUrl: "#",
        description: "Groww offers a fast-paced frontend internship. You will pixel-perfect UI screens and add micro-interactions that make the app feel incredibly smooth."
    },
    {
        id: "job-57",
        title: "Backend Developer",
        company: "Dunzo",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Flask", "MongoDB"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Dunzo's core logistics team is looking for a backend engineer. Handling sudden bursts of high-traffic and optimizing routing algorithm latency is your primary goal."
    },
    {
        id: "job-58",
        title: "Junior Backend Developer",
        company: "Zerodha",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Golang", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "#",
        description: "Zerodha loves Golang. We want a junior backend developer to aid in building ultra-low latency microservices for our kite trading platform."
    },
    {
        id: "job-59",
        title: "Java Developer (0-1)",
        company: "Accenture",
        location: "Gurugram",
        mode: "Remote",
        experience: "0-1",
        skills: ["Java", "Spring", "SQL"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "Accenture requires junior Java resources immediately for a telecom domain project. Experience in building REST endpoints and writing JUnit tests is necessary."
    },
    {
        id: "job-60",
        title: "SDE Intern",
        company: "Postman",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["JavaScript", "Node.js", "Jest"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹40k/month Internship",
        applyUrl: "#",
        description: "Postman is hiring an SDE intern to help maintain our open-source tools. You'll review community PRs and write massive amounts of unit tests."
    }
];

// Provide function to get jobs to make it globally available
function getJobsData() {
    return jobsData;
}
